name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Semantic Release
      uses: codfish/semantic-release-action@master
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
      with:
        branch: scottperham-actions-1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test
    - name: Pack
      run: dotnet pack /p:version=${{ steps.semantic.outputs.new_release_version }}
    
